---
- name: Deploy systemd service for training
  hosts: "clients"
  become: yes
  tasks:
    - name: Copy private-key
      copy:
        src: ssh-keys/id_rsa
        dest: /root/.ssh/id_rsa
        owner: root 
        group: root
        mode: '0600'
